name: CI
on:
  push:
    branches:
      - master
      - develop
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install deps
      run: npm ci
    - name: Run build
      run: npm run build
    - name: Run tests
      run: npm run test
    - name: Run sonar analysis
      uses: sonarsource/sonarcloud-github-action@v2.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}